
# DATABASE ??
    h2:
        console:
        enabled: true
        path: /h2-console

    datasource:
        url: jdbc:h2:~/local2
        driverClassName: org.h2.Driver
        username: sa
        password: ""

# JPA ??
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
                show_sql: false
        hibernate:
            ddl-auto: create

# AWS S3 ??
cloud:
    aws:
        s3:
            bucket: nyumbucket
        stack:
            auto: false
        region:
            static: ap-northeast-2
        credentials:
            accessKey: ${AWS_ACCESS_KEY_ID}
            secretKey: ${AWS_SECRET_ACCESS_KEY}
