# Spring configuration import
spring:

    datasource:
        url: jdbc:h2:~/local2
        driverClassName: org.h2.Driver
        username: sa
        password: ""
    h2:
        console:
            enabled: true
            path: /h2-console


    # JPA ??
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
                show_sql: false
        hibernate:
            ddl-auto: update

    flyway:
        enabled: true
        url: jdbc:mysql://localhost:3306/your_database
        user: your_db_user
        password: your_db_password
        locations: classpath:db/migration
        baseline-on-migrate: true

# AWS S3 ??
cloud:
    aws:
        s3:
            bucket: timecapsule2
        stack:
            auto: false
        region:
            static: ap-northeast-2
        credentials:
            accessKey: ${AWS_ACCESS_KEY_ID}
            secretKey: ${AWS_SECRET_ACCESS_KEY}

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        enabled: true