name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.1.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Spring Boot 애플리케이션 빌드
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # Docker 이미지 빌드
    - name: Docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test .

    # DockerHub 로그인 (이미지 푸시를 위해)
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Docker Hub로 이미지 푸시
    - name: Docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

  # EC2에서 이미지를 풀받아 실행
  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:
    - name: Docker pull
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

    - name: Docker stop and remove container
      run: |
        if [ $(docker ps -q -f name=spring-cicd-test) ]; then
          docker stop spring-cicd-test
          docker rm spring-cicd-test
        fi

    - name: Docker run new container
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        docker run -d -p 80:8080 \
          -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
          -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
          --name spring-cicd-test \
          ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd-test

    - name: 컨테이너 상태 확인
      run: docker ps -a

    - name: 컨테이너 로그 확인
      run: docker logs spring-cicd-test || true

    - name: 불필요한 Docker 이미지 삭제
      run: docker image prune -f
